export default [
    {
        id: 1,
        title: 'Mới phát gần đây',
        albums: [
            {
                id: 1,
                name: 'Hoa Hải Đường',
                imageUri: require('~/Assets/albums/HoaHaiDuong.jpg'),
                artists: 'Jack - J97',
                songs: [
                    {
                        id: 1,
                        name: 'Bên Trên Tầng Lầu - Lofi Version',
                        uri: require('~/Assets/music/BenTrenTangLau-TangDuyTan.mp3'),
                        imageUri: require('~/Assets/songs/BenTrenTangLau.jpg'),
                        artists: 'Tăng Duy Tân',
                    },
                    {
                        id: 2,
                        name: 'Ngôi Sao Cô Đơn',
                        uri: require('~/Assets/music/NgoiSaoCoDon-JackJ97.mp3'),
                        imageUri: require('~/Assets/songs/NgoiSaoCoDon.jpg'),
                        artists: 'Jack - J97',
                    },
                ],
            },
            {
                id: 2,
                name: 'Ngôi Sao Cô Đơn',
                imageUri: require('~/Assets/albums/NgoiSaoCoDon.jpg'),
                artists: 'Jack - J97',
                songs: [
                    {
                        id: 1,
                        name: 'Ngôi Sao Cô Đơn',
                        uri: require('~/Assets/music/NgoiSaoCoDon-JackJ97.mp3'),
                        imageUri: require('~/Assets/songs/NgoiSaoCoDon.jpg'),
                        artists: 'Jack - J97',
                    },
                ],
            },
            {
                id: 3,
                name: 'Quên Anh Đi',
                imageUri: require('~/Assets/albums/QuenAnhDi.jpg'),
                artists: 'MONO',
                songs: [],
            },
        ],
    },
    {
        id: 2,
        title: 'Tuyển tập hàng đầu của bạn',
        albums: [
            {
                id: 1,
                name: 'Tuyển tập của Maroon 5',
                imageUri: require('~/Assets/albums/maroon5-mix.jpg'),
                artists: 'Ed Sheeran, Camila Cabello, Christina Aguilera và nhiều nghệ sĩ khác',
                songs: [
                        {
                            id: 1,
                            name: 'Ngôi Sao Cô Đơn',
                            uri: require('~/Assets/music/NgoiSaoCoDon-JackJ97.mp3'),
                            imageUri: require('~/Assets/songs/NgoiSaoCoDon.jpg'),
                            artists: 'Jack - J97',
                        },
                        {
                            id: 2,
                            name: 'Bên Trên Tầng Lầu - Lofi Version',
                            uri: require('~/Assets/music/BenTrenTangLau-TangDuyTan.mp3'),
                            imageUri: require('~/Assets/songs/BenTrenTangLau.jpg'),
                            artists: 'Tăng Duy Tân',
                        },
                        {
                            id: 3,
                            name: 'Waiting For You',
                            uri: require('~/Assets/music/WaitingForYou-MONOOnion.mp3'),
                            imageUri: require('~/Assets/songs/WaitingForYou.jpg'),
                            artists: 'MONO',
                        },
                        {
                            id: 4,
                            name: 'TÌNH ĐẦU LOFI VERS - CryZ T MIX',
                            uri: require('~/Assets/music/TinhDau-TangDuyTan.mp3'),
                            imageUri: require('~/Assets/songs/TinhDau.jpg'),
                            artists: 'Rain Radio, Tang Duy Tan',
                        },
                        {
                            id: 5,
                            name: 'Yêu Đơn Phương',
                            uri: require('~/Assets/music/YeuDonPhuong-OnlyC.mp3'),
                            imageUri: require('~/Assets/songs/YeuDonPhuong.jpg'),
                            artists: 'Only C, Karik',
                        },
                        {
                            id: 6,
                            name: 'Quên Anh Đi',
                            uri: require('~/Assets/music/QuenAnhDi-MONO.mp3'),
                            imageUri: require('~/Assets/songs/QuenAnhDi.jpg'),
                            artists: 'MONO',
                        },
                        {
                            id: 7,
                            name: 'Phía Sau Một Cô Gái (feat. Soobin Hoàng Sơn)',
                            uri: require('~/Assets/music/PhiaSauMotCoGai-SoobinHoangSon.mp3'),
                            imageUri: require('~/Assets/songs/PhiaSauMotCoGai.jpg'),
                            artists: 'SOOBIN',
                        },
                        {
                            id: 8,
                            name: "There's No One At All (Another Version)",
                            uri: require('~/Assets/music/TheresNoOneAtAllAnotherVersion-SonTungMTP.mp3'),
                            imageUri: require('~/Assets/songs/TheresNoOneAtAll.jpg'),
                            artists: 'Sơn Tùng M-TP',
                        },
                        {
                            id: 9,
                            name: 'Người Âm Phủ',
                            uri: require('~/Assets/music/NguoiAmPhu-Osad.mp3'),
                            imageUri: require('~/Assets/songs/NguoiAmPhu.jpg'),
                            artists: 'Osad, VRT',
                        },
                        {
                            id: 10,
                            name: 'Còn Gì Đau Hơn Chữ Đã Từng',
                            uri: require('~/Assets/music/ConGiDauHonChuDaTung-QuanAP.mp3'),
                            imageUri: require('~/Assets/songs/ConGiDauHonChuDaTung.jpg'),
                            artists: 'Quân A.P',
                        },
                    ],
            },
            {
                
                id: 2,
                name: 'Tuyển tập của Rain Radio',
                imageUri: require('~/Assets/albums/rain-radio-mix.jpg'),
                artists: 'Nguyên, Freak D, Phúc Chinh và nhiều nghệ sĩ khác',
                songs:  [
                    {
                        id: 1,
                        name: 'Ngôi Sao Cô Đơn',
                        uri: require('~/Assets/music/NgoiSaoCoDon-JackJ97.mp3'),
                        imageUri: require('~/Assets/songs/NgoiSaoCoDon.jpg'),
                        artists: 'Jack - J97',
                    },
                    {
                        id: 2,
                        name: 'Bên Trên Tầng Lầu - Lofi Version',
                        uri: require('~/Assets/music/BenTrenTangLau-TangDuyTan.mp3'),
                        imageUri: require('~/Assets/songs/BenTrenTangLau.jpg'),
                        artists: 'Tăng Duy Tân',
                    },
                    {
                        id: 3,
                        name: 'Waiting For You',
                        uri: require('~/Assets/music/WaitingForYou-MONOOnion.mp3'),
                        imageUri: require('~/Assets/songs/WaitingForYou.jpg'),
                        artists: 'MONO',
                    },
                    {
                        id: 4,
                        name: 'TÌNH ĐẦU LOFI VERS - CryZ T MIX',
                        uri: require('~/Assets/music/TinhDau-TangDuyTan.mp3'),
                        imageUri: require('~/Assets/songs/TinhDau.jpg'),
                        artists: 'Rain Radio, Tang Duy Tan',
                    },
                    {
                        id: 5,
                        name: 'Yêu Đơn Phương',
                        uri: require('~/Assets/music/YeuDonPhuong-OnlyC.mp3'),
                        imageUri: require('~/Assets/songs/YeuDonPhuong.jpg'),
                        artists: 'Only C, Karik',
                    },
                    {
                        id: 6,
                        name: 'Quên Anh Đi',
                        uri: require('~/Assets/music/QuenAnhDi-MONO.mp3'),
                        imageUri: require('~/Assets/songs/QuenAnhDi.jpg'),
                        artists: 'MONO',
                    },
                    {
                        id: 7,
                        name: 'Phía Sau Một Cô Gái (feat. Soobin Hoàng Sơn)',
                        uri: require('~/Assets/music/PhiaSauMotCoGai-SoobinHoangSon.mp3'),
                        imageUri: require('~/Assets/songs/PhiaSauMotCoGai.jpg'),
                        artists: 'SOOBIN',
                    },
                    {
                        id: 8,
                        name: "There's No One At All (Another Version)",
                        uri: require('~/Assets/music/TheresNoOneAtAllAnotherVersion-SonTungMTP.mp3'),
                        imageUri: require('~/Assets/songs/TheresNoOneAtAll.jpg'),
                        artists: 'Sơn Tùng M-TP',
                    },
                    {
                        id: 9,
                        name: 'Người Âm Phủ',
                        uri: require('~/Assets/music/NguoiAmPhu-Osad.mp3'),
                        imageUri: require('~/Assets/songs/NguoiAmPhu.jpg'),
                        artists: 'Osad, VRT',
                    },
                    {
                        id: 10,
                        name: 'Còn Gì Đau Hơn Chữ Đã Từng',
                        uri: require('~/Assets/music/ConGiDauHonChuDaTung-QuanAP.mp3'),
                        imageUri: require('~/Assets/songs/ConGiDauHonChuDaTung.jpg'),
                        artists: 'Quân A.P',
                    },
                ],
            },
            {
                id: 3,
                name: 'Tuyển tập nhạc thư giãn',
                imageUri: require('~/Assets/albums/chill-mix.jpg'),
                artists: 'Jack - J97, Quân A.P, MONO và nhiều nghệ sĩ khác',
                time: '3 giờ 26 phút',
                songs: [
                    {
                        id: 1,
                        name: 'Ngôi Sao Cô Đơn',
                        uri: require('~/Assets/music/NgoiSaoCoDon-JackJ97.mp3'),
                        imageUri: require('~/Assets/songs/NgoiSaoCoDon.jpg'),
                        artists: 'Jack - J97',
                    },
                    {
                        id: 2,
                        name: 'Bên Trên Tầng Lầu - Lofi Version',
                        uri: require('~/Assets/music/BenTrenTangLau-TangDuyTan.mp3'),
                        imageUri: require('~/Assets/songs/BenTrenTangLau.jpg'),
                        artists: 'Tăng Duy Tân',
                    },
                    {
                        id: 3,
                        name: 'Waiting For You',
                        uri: require('~/Assets/music/WaitingForYou-MONOOnion.mp3'),
                        imageUri: require('~/Assets/songs/WaitingForYou.jpg'),
                        artists: 'MONO',
                    },
                    {
                        id: 4,
                        name: 'TÌNH ĐẦU LOFI VERS - CryZ T MIX',
                        uri: require('~/Assets/music/TinhDau-TangDuyTan.mp3'),
                        imageUri: require('~/Assets/songs/TinhDau.jpg'),
                        artists: 'Rain Radio, Tang Duy Tan',
                    },
                    {
                        id: 5,
                        name: 'Yêu Đơn Phương',
                        uri: require('~/Assets/music/YeuDonPhuong-OnlyC.mp3'),
                        imageUri: require('~/Assets/songs/YeuDonPhuong.jpg'),
                        artists: 'Only C, Karik',
                    },
                    {
                        id: 6,
                        name: 'Quên Anh Đi',
                        uri: require('~/Assets/music/QuenAnhDi-MONO.mp3'),
                        imageUri: require('~/Assets/songs/QuenAnhDi.jpg'),
                        artists: 'MONO',
                    },
                    {
                        id: 7,
                        name: 'Phía Sau Một Cô Gái (feat. Soobin Hoàng Sơn)',
                        uri: require('~/Assets/music/PhiaSauMotCoGai-SoobinHoangSon.mp3'),
                        imageUri: require('~/Assets/songs/PhiaSauMotCoGai.jpg'),
                        artists: 'SOOBIN',
                    },
                    {
                        id: 8,
                        name: "There's No One At All (Another Version)",
                        uri: require('~/Assets/music/TheresNoOneAtAllAnotherVersion-SonTungMTP.mp3'),
                        imageUri: require('~/Assets/songs/TheresNoOneAtAll.jpg'),
                        artists: 'Sơn Tùng M-TP',
                    },
                    {
                        id: 9,
                        name: 'Người Âm Phủ',
                        uri: require('~/Assets/music/NguoiAmPhu-Osad.mp3'),
                        imageUri: require('~/Assets/songs/NguoiAmPhu.jpg'),
                        artists: 'Osad, VRT',
                    },
                    {
                        id: 10,
                        name: 'Còn Gì Đau Hơn Chữ Đã Từng',
                        uri: require('~/Assets/music/ConGiDauHonChuDaTung-QuanAP.mp3'),
                        imageUri: require('~/Assets/songs/ConGiDauHonChuDaTung.jpg'),
                        artists: 'Quân A.P',
                    },
                ],
            },
            {
                id: 4,
                name: 'Tuyển tập nhạc vui vẻ',
                imageUri: require('~/Assets/albums/happy-mix.jpg'),
                artists: 'Ed Sheeran, Maroon 5 và nhiều nghệ sĩ khác',
                songs: [],
            },
            {
                id: 5,
                name: 'Tuyển tập nhạc Hip-Hop',
                imageUri: require('~/Assets/albums/hiphop-mix.jpg'),
                artists: 'Andree Right Hand, Rapital, MANBO và nhiều nghệ sĩ khác',
                songs: [],
            },
            // {
            //     id: 6,
            //     name: 'Tuyển tập nhạc Pop',
            //     imageUri: require('~/Assets/albums/pop-mix.jpg'),
            //     artists: 'Ed Sheeran, Maroon 5 và nhiều nghệ sĩ khác',
            //     songs: [],
            // },
        ],
    },
    {
        id: 3,
        title: 'Bài hát dành cho bạn',
        albums: [
            {
                id: 1,
                imageUri: require('~/Assets/albums/daily-mix1.jpg'),
                artists: 'Rain Radio, Vu Trung Quan, Reddy và nhiều hơn nữa',
                songs: [],
            },
            {
                id: 2,
                imageUri: require('~/Assets/albums/daily-mix2.jpg'),
                artists: 'Maroon 5, Alan Walker, Ed Sheeran và nhiều hơn nữa',
                songs: [],
            },
            {
                id: 3,
                imageUri: require('~/Assets/albums/discover-weekly.jpg'),
                artists:
                    'Tuyển tập nhạc mới hàng tuần. Thưởng thức ca khúc mới và ít người nghe dành cho bạn. Cập nhật mỗi thứ Hai.',
                songs: [],
            },
            {
                id: 4,
                imageUri: require('~/Assets/albums/new.jpg'),
                artists:
                    'Nhún nhảy theo những giai điệu mới toanh từ nghệ sĩ bạn theo dõi và đĩa đơn mới dành cho bạn. Cập nhật mỗi thứ Sáu.',
                songs: [],
            },
        ],
    },
    {
        id: 4,
        title: 'Tuyển tập nhạc hay nhất của các nghệ sĩ',
        albums: [
            {
                id: 1,
                imageUri: require('~/Assets/albums/this-is-maroon5.jpg'),
                artists: 'From Songs About Jane to JORDI, find their latest releases here!',
                songs: [],
            },
            {
                id: 2,
                imageUri: require('~/Assets/albums/this-is-edsheeran.jpg'),
                artists: 'All his biggest hits, in one place.',
                songs: [],
            },
            {
                id: 3,
                imageUri: require('~/Assets/albums/this-is-alanwalker.jpg'),
                artists: 'The essential Alan Walker tracks and remixes.',
                songs: [],
            },
        ],
    },
    {
        id: 5,
        title: 'Chương trình đáng để thử',
        albums: [
            {
                id: 1,
                name: 'Rintik Sedu',
                job: '',
                imageUri: require('~/Assets/albums/rintik-sedu.jpg'),
                artists: 'Rintiksedu',
                songs: [],
            },
            {
                id: 2,
                name: 'Kita dan Waktu',
                job: '',
                imageUri: require('~/Assets/albums/kita-dan-waktu.jpg'),
                artists: 'helobagas',
                songs: [],
            },
            {
                id: 3,
                name: 'Sunhuyn Podcast',
                job: 'Giáo dục',
                imageUri: require('~/Assets/albums/sunhyun-podcast.jpg'),
                artists: 'Sunhuyn',
                songs: [],
            },
            {
                id: 4,
                name: 'Hideo Kojima presents Brain Structure',
                job: 'Giải trí',
                imageUri: require('~/Assets/albums/hideo-kojima.jpg'),
                artists: 'Spotify Studios',
                songs: [],
            },
            {
                id: 5,
                name: 'Sách nói mỗi ngày',
                job: 'Nghệ thuật',
                imageUri: require('~/Assets/albums/sach-noi.jpg'),
                artists: 'Nu Pham',
                songs: [],
            },
            // {
            //     id: 6,
            //     name: 'NHI LE',
            //     job: 'Giáo dục',
            //     imageUri: require('~/Assets/albums/nhi-le.jpg'),
            //     artists: 'Là chính mình',
            //     songs: [],
            // },
            // {
            //     id: 7,
            //     name: 'Luyện Nghe Tiếng Anh Hàng Ngày - Ms Thuỷ KISS English',
            //     job: 'Giáo dục',
            //     imageUri: require('~/Assets/albums/luyen-nghe-tieng-anh.jpg'),
            //     artists: 'Ms Thuỷ',
            //     songs: [],
            // },
            // {
            //     id: 8,
            //     name: 'Chill Box 20s',
            //     job: 'Lối sống & sức khỏe * Xã hội',
            //     imageUri: require('~/Assets/albums/chill-box.jpg'),
            //     artists: 'Chill Box 20s',
            //     songs: [],
            // },
            // {
            //     id: 9,
            //     name: 'Đắc Nhân Tâm (Bản FULL tại Voiz FM - Ứng dụng Sách nói & Podcast chất lượng cao)',
            //     job: 'Nghệ thuật',
            //     imageUri: require('~/Assets/albums/dac-nhan-tam.jpg'),
            //     artists: 'Voiz FM & Thư viện Sách nói First News',
            //     songs: [],
            // },
        ],
    },
    {
        id: 6,
        title: 'Bảng xếp hạng',
        albums: [
            {
                id: 1,
                imageUri: require('~/Assets/albums/top-50-vietnam.jpg'),
                artists: 'Thông tin cập nhật hằng ngày về những bản nhạc được nghe nhiều nhất hiện nay tại Việt Nam.',
                songs: [],
            },
            {
                id: 2,
                imageUri: require('~/Assets/albums/top-50-global.jpg'),
                artists: 'Thông tin cập nhật hằng ngày về những bản nhạc được nghe nhiều nhất hiện nay tại Toàn Cầu.',
                songs: [],
            },
            {
                id: 3,
                imageUri: require('~/Assets/albums/hot-hit-vietnam.jpg'),
                artists: 'Đông tới Tây, đây là những ca khúc thịnh hành nhất ở Việt Nam. Ảnh bìa: RPT MCK',
                songs: [],
            },
        ],
    },
    {
        id: 7,
        title: 'Lựa chọn của Spotify',
        albums: [
            {
                id: 1,
                name: 'EQUAL Vietnam',
                imageUri: require('~/Assets/albums/equal-vietnam.jpg'),
                artists: 'Cùng tôn vinh tài năng và âm nhạc của những nữ nghệ sĩ Việt. Ảnh bìa: Chi Pu',
                songs: [],
            },
            {
                id: 2,
                name: 'New Music Friday Vietnam',
                imageUri: require('~/Assets/albums/new-music.jpg'),
                artists: 'Những chiếc nhạc mới trong tuần, được tuyển chọn cẩn thận. Ảnh bìa: Ha Le',
                songs: [],
            },
            {
                id: 3,
                name: 'EQUAL Global ',
                imageUri: require('~/Assets/albums/equal-global.jpg'),
                artists: 'Listen to women from all over the world, at full volume. Cover: Shania Twain',
                songs: [],
            },
            {
                id: 4,
                name: 'Hot Hits Vietnam',
                imageUri: require('~/Assets/albums/hot-hit-vietnam.jpg'),
                artists: 'Đông tới Tây, đây là những ca khúc thịnh hành nhất ở Việt Nam. Ảnh bìa: RPT MCK',
                songs: [],
            },
            {
                id: 5,
                name: 'Thiên Hạ Nghe Gì',
                imageUri: require('~/Assets/albums/thien-ha-nghe-gi.jpg'),
                artists: 'Những gì mà người bên cạnh bạn đang nghe. Ảnh bìa: Phan Mạnh Quỳnh',
                songs: [],
            },
            // {
            //     id: 6,
            //     name: 'Pop Rising Vietnam',
            //     imageUri: require('~/Assets/albums/pop-rising-vietnam.jpg'),
            //     artists: 'Những ca khúc sắp thịnh hành khắp các mặt trận. Ảnh bìa: Ed Sheeran',
            //     songs: [],
            // },
            // {
            //     id: 7,
            //     name: 'V-Pop Không Thể Thiếu',
            //     imageUri: require('~/Assets/albums/vpop-khong-the-thieu.jpg'),
            //     artists: 'V-Pop đã đơm hoa trên những khúc ca này. Ảnh bìa: Đức Phúc',
            //     songs: [],
            // },
            // {
            //     id: 8,
            //     name: 'KimBops!',
            //     imageUri: require('~/Assets/albums/kim-bops.jpg'),
            //     artists:
            //         "Rolling with the 'bops' in your Kimbap. Bringing you the songs that are currently trending and everything else in between. Cover: NewJeans",
            //     songs: [],
            // },
        ],
    },
];